# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlinks',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='specialcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
