# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20170805_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantlinks',
            options={'verbose_name': 'Link importante', 'verbose_name_plural': 'Links importantes'},
        ),
        migrations.AlterModelOptions(
            name='specialcategory',
            options={'verbose_name': 'Categoria especial', 'verbose_name_plural': 'Categorias especiais'},
        ),
    ]
