# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20170809_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcategory',
            name='show_right',
            field=models.BooleanField(default=False, verbose_name='Exibir junto com links importantes?'),
        ),
        migrations.AlterField(
            model_name='importantlinks',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='specialcategory',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
